version: '3'
services:
  gocd-server:
    image: gocd/gocd-server:v19.5.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./config/cruise-config.xml:/godata/config/cruise-config.xml
  gocd-agent:
    image: gocd/gocd-agent-centos-7:v19.5.0
    environment:
      AGENT_AUTO_REGISTER_KEY: e2448426-f0a5-47d7-ad24-baea0d138215
      GO_SERVER_URL: https://gocd-server:8154/go
      # pass on environment variables from the host:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_SECURITY_TOKEN:
      AWS_REGION:
      AWS_DEFAULT_REGION:
volumes:
  gitlab-config:
  gitlab-data:
